name: Build and Save Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: payment-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: payment-jar

      - name: Verify Artifact
        run: ls -lrt
