name: Artifact Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: echo "Hello World" > sample.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-file
          path: sample.txt
